let hourChart, platformChart, mentionChart, redTrendChart, topicOwnChart, topicTrendsChart;
let incidentMap;
let mode = '24h';

// In-memory cache of the latest fetched comment lists + history, so the modal
// and the red-list panel don't need to re-fetch on every interaction.
const state = {
  socialSignals: null,
  comments: { facebook: [], instagram: [], threads: [] },
  history: { facebook: [], instagram: [], threads: [] },
  topicHeat: null,
  selectedTopicId: null,
};

const LIGHT_ICON = { '紅':'🔴', '黃':'🟡', '綠':'🟢' };
const PLATFORM_LABEL = { facebook: 'Facebook', instagram: 'Instagram', threads: 'Threads' };
const RED_RATIO_ALERT = 0.25;     // 25%: show red banner
const YELLOW_RATIO_WARN = 0.40;   // 40% non-green: yellow banner

const DEFAULT_HOTSPOTS = [
  {
    title: '台中槍案',
    place: '台中市西區府後街',
    lat: 24.1388,
    lng: 120.6697,
    level: 'red',
    source: 'news',
    platform: '新聞',
    note: '社會治安高關注事件'
  }
];

const COMMENT_EVENT_RULES = [
  {
    title: '廚餘山',
    place: '台中市霧峰區',
    lat: 24.046,
    lng: 120.698,
    level: 'red',
    keywords: ['廚餘山', '廚餘']
  },
  {
    title: '垃圾山',
    place: '台中市大里區',
    lat: 24.104,
    lng: 120.69,
    level: 'red',
    keywords: ['垃圾山', '垃圾掩埋場']
  },
  {
    title: '捷運藍線爭議',
    place: '台中市政府（西屯）',
    lat: 24.1617,
    lng: 120.6469,
    level: 'yellow',
    keywords: ['捷運', '藍線']
  },
  {
    title: '行人地獄討論',
    place: '台中市中區',
    lat: 24.1402,
    lng: 120.6839,
    level: 'yellow',
    keywords: ['行人地獄']
  }
];

const LOCATION_HINTS = [
  { k: '府後街', place: '台中市西區府後街', lat: 24.1388, lng: 120.6697 },
  { k: '霧峰', place: '台中市霧峰區', lat: 24.046, lng: 120.698 },
  { k: '大里', place: '台中市大里區', lat: 24.104, lng: 120.69 },
  { k: '西屯', place: '台中市西屯區', lat: 24.1818, lng: 120.6252 },
  { k: '西區', place: '台中市西區', lat: 24.1437, lng: 120.6626 }
];

function lightLevelByCount(c, avg){
  if(c >= Math.max(10, avg*1.8)) return '紅';
  if(c >= Math.max(5, avg*1.2)) return '黃';
  return '綠';
}

function upsertChart(instance, ctx, config){
  if(instance){ instance.data=config.data; instance.options=config.options; instance.update(); return instance; }
  return new Chart(ctx, config);
}

// Shared tooltip style matching the dashboard's dark theme.
// Pass { callbacks: {...}, mode, displayColors } etc. to override.
function darkTooltip(overrides){
  return Object.assign({
    backgroundColor: 'rgba(18, 25, 53, 0.96)',
    borderColor: '#5a79ff',
    borderWidth: 1,
    titleColor: '#d8e2ff',
    bodyColor: '#e8ecff',
    padding: 10,
    cornerRadius: 8,
    titleFont: { weight: '600', size: 13 },
    bodyFont: { size: 13 },
    displayColors: true,      // default true so multi-series charts still show color dots
    intersect: false,
  }, overrides || {});
}

// For line/bar charts with a time/category x-axis: "hover anywhere on x" behavior.
const INDEX_HOVER = { mode: 'index', intersect: false, axis: 'x' };

function pick(d, key24, key7){ return mode==='7d' ? (d[key7] ?? d[key24]) : d[key24]; }

function escapeHtml(s){
  return String(s ?? '').replace(/[&<>"']/g, c => (
    { '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' }[c]
  ));
}

// --------- Data fetching ---------
async function fetchJSON(path){
  try {
    const r = await fetch(path + '?t=' + Date.now());
    if (!r.ok) return null;
    return await r.json();
  } catch { return null; }
}

async function fetchLiveNews(){
  // Stable mode: read prebuilt feed generated by GitHub Actions.
  // Avoids browser-side CORS/proxy instability.
  const arr = await fetchJSON('./live_news.json');
  return Array.isArray(arr) ? arr : [];
}

// --------- Social signal cards (clickable) ---------
function renderSocialCards(){
  const wrap = document.getElementById('socialSignals');
  if (!wrap) return;
  wrap.innerHTML = '';
  const ss = state.socialSignals || {};
  ['facebook', 'instagram', 'threads'].forEach(p => {
    const s = ss[p] || { total: 0, red: 0, yellow: 0, green: 0, updated_at: '-' };
    const btn = document.createElement('button');
    btn.type = 'button';
    btn.className = 'social-card';
    btn.setAttribute('aria-label', `${PLATFORM_LABEL[p]} 留言明細`);
    btn.innerHTML = `
      <h3>${PLATFORM_LABEL[p]}（總留言 ${s.total || 0}）</h3>
      <div class="social-row"><span class="tag">🔴 紅燈</span><strong>${s.red || 0}</strong></div>
      <div class="social-row"><span class="tag">🟡 黃燈</span><strong>${s.yellow || 0}</strong></div>
      <div class="social-row"><span class="tag">🟢 綠燈</span><strong>${s.green || 0}</strong></div>
      <div class="social-row" style="opacity:.75;font-size:12px"><span>更新</span><span>${escapeHtml(s.updated_at || '-')}</span></div>
      <div class="drill-hint">▸ 點擊查看完整留言</div>
    `;
    btn.addEventListener('click', () => openModal(p, 'all'));
    wrap.appendChild(btn);
  });
}

// --------- Red-ratio alert ---------
function updateAlertBanner(){
  const el = document.getElementById('alertBanner');
  if (!el) return;
  const ss = state.socialSignals || {};
  const redPlatforms = [];
  const warnPlatforms = [];
  ['facebook','instagram','threads'].forEach(p => {
    const s = ss[p] || {};
    const total = Number(s.total) || 0;
    if (!total) return;
    const redPct = total ? (Number(s.red) || 0) / total : 0;
    const nonGreenPct = total ? ((Number(s.red) || 0) + (Number(s.yellow) || 0)) / total : 0;
    if (redPct >= RED_RATIO_ALERT) redPlatforms.push({p, redPct});
    else if (nonGreenPct >= YELLOW_RATIO_WARN) warnPlatforms.push({p, nonGreenPct});
  });
  if (redPlatforms.length){
    el.classList.remove('hidden', 'level-yellow');
    el.classList.add('level-red');
    const chips = redPlatforms.map(x =>
      `<span class="chip">${PLATFORM_LABEL[x.p]} 紅 ${(x.redPct*100).toFixed(1)}%</span>`
    ).join('');
    el.innerHTML = `
      <span class="icon">🚨</span>
      <span class="msg">紅燈留言占比達警示門檻（≥${(RED_RATIO_ALERT*100)}%）。建議立即檢視紅燈留言清單。</span>
      <span class="platform-chips">${chips}</span>
    `;
  } else if (warnPlatforms.length){
    el.classList.remove('hidden', 'level-red');
    el.classList.add('level-yellow');
    const chips = warnPlatforms.map(x =>
      `<span class="chip">${PLATFORM_LABEL[x.p]} 非綠 ${(x.nonGreenPct*100).toFixed(1)}%</span>`
    ).join('');
    el.innerHTML = `
      <span class="icon">⚠️</span>
      <span class="msg">非綠燈（紅+黃）占比偏高，請關注輿情走向。</span>
      <span class="platform-chips">${chips}</span>
    `;
  } else {
    el.classList.add('hidden');
    el.classList.remove('level-red', 'level-yellow');
    el.innerHTML = '';
  }
}

// --------- Red-ratio trend chart (historical) ---------
function renderRedTrendChart(){
  const canvas = document.getElementById('redTrendChart');
  if (!canvas) return;
  const hist = state.history || {};
  const fmtLabel = (iso) => (iso || '').slice(5, 16).replace('T', ' ');

  // Build unified x-axis from the union of timestamps
  const allTs = new Set();
  ['facebook','instagram','threads'].forEach(p => (hist[p] || []).forEach(x => allTs.add(x.ts)));
  const labels = Array.from(allTs).sort();
  const series = {
    facebook: new Map((hist.facebook||[]).map(x => [x.ts, x.red_pct])),
    instagram: new Map((hist.instagram||[]).map(x => [x.ts, x.red_pct])),
    threads: new Map((hist.threads||[]).map(x => [x.ts, x.red_pct])),
  };
  const datasets = [
    { label: 'Facebook', color: '#4f8cff' },
    { label: 'Instagram', color: '#e83e8c' },
    { label: 'Threads', color: '#ffc107' },
  ].map(({label, color}) => {
    const key = label.toLowerCase();
    return {
      label,
      data: labels.map(ts => series[key].get(ts) ?? null),
      borderColor: color,
      backgroundColor: color + '33',
      tension: 0.3,
      spanGaps: true,
    };
  });

  // Enhance dataset styling for nicer hover markers
  datasets.forEach(ds => {
    ds.pointRadius = 0;
    ds.pointHoverRadius = 5;
    ds.pointHoverBackgroundColor = '#fff';
    ds.pointHoverBorderColor = ds.borderColor;
    ds.pointHoverBorderWidth = 2;
    ds.borderWidth = 1.8;
  });
  redTrendChart = upsertChart(redTrendChart, canvas, {
    type: 'line',
    data: { labels: labels.map(fmtLabel), datasets },
    options: {
      interaction: INDEX_HOVER,
      hover: INDEX_HOVER,
      plugins: {
        legend: { labels: { color: '#b9c3f2' } },
        tooltip: darkTooltip({
          mode: 'index',
          callbacks: {
            label: (ctx) => ` ${ctx.dataset.label}：${ctx.parsed.y == null ? '—' : ctx.parsed.y.toFixed(1) + '%'}`,
          },
        }),
      },
      scales: {
        x: { ticks: { color: '#b9c3f2', maxRotation: 30 } },
        y: { ticks: { color: '#b9c3f2', callback: v => v + '%' }, beginAtZero: true, suggestedMax: 50 },
      },
    }
  });
}

// --------- Red comments panel (grouped by platform) ---------
function renderRedCommentsPanel(){
  const wrap = document.getElementById('redComments');
  if (!wrap) return;
  wrap.innerHTML = '';
  let anyShown = false;
  ['facebook','instagram','threads'].forEach(p => {
    const reds = (state.comments[p] || []).filter(c => c.signal === 'red');
    if (!reds.length) return;
    anyShown = true;
    const group = document.createElement('div');
    group.className = 'red-group';
    const title = document.createElement('h3');
    title.textContent = `${PLATFORM_LABEL[p]}（${reds.length} 則）`;
    group.appendChild(title);
    const ul = document.createElement('ul');
    reds.slice(0, 30).forEach(c => {
      const li = document.createElement('li');
      const authorHtml = `<span class="author">${escapeHtml(c.author || '匿名')}</span>` +
                        (c.time_text ? `<span class="when">（${escapeHtml(c.time_text)}）</span>` : '');
      let textHtml = escapeHtml(c.text || '');
      if (c.url) {
        textHtml = `<a href="${escapeHtml(c.url)}" target="_blank" rel="noopener">${textHtml}</a>`;
      }
      li.innerHTML = `${authorHtml}<br/>${textHtml}`;
      ul.appendChild(li);
    });
    if (reds.length > 30) {
      const more = document.createElement('li');
      more.style.opacity = '.7';
      more.textContent = `... 另 ${reds.length - 30} 筆（點擊上方卡片查看完整清單）`;
      ul.appendChild(more);
    }
    group.appendChild(ul);
    wrap.appendChild(group);
  });
  if (!anyShown){
    wrap.innerHTML = '<p class="hint">目前無紅燈留言。</p>';
  }
}

// --------- Topic heat (Google Trends iframe + our-data chart) ---------
// Link to the public Google Trends explore page (opens in a new tab).
// trends.google.com blocks iframe embedding from most origins, so we link out
// instead of iframing — cleaner and always works.
function buildTrendsExploreUrl(topic){
  const q = encodeURIComponent(topic.trends_keyword);
  const geo = encodeURIComponent(topic.geo || 'TW');
  const date = encodeURIComponent(topic.time_range || 'today 5-y');
  return `https://trends.google.com/trends/explore?date=${date}&geo=${geo}&q=${q}&hl=zh-TW`;
}

function renderTopicHeat(){
  const heat = state.topicHeat;
  if (!heat || !heat.topics || !heat.topics.length) return;
  const sel = document.getElementById('topicSelect');
  if (!sel) return;
  // Rebuild select options only if changed
  const existingIds = Array.from(sel.options).map(o => o.value).join(',');
  const newIds = heat.topics.map(t => t.id).join(',');
  if (existingIds !== newIds){
    sel.innerHTML = '';
    heat.topics.forEach(t => {
      const opt = document.createElement('option');
      opt.value = t.id; opt.textContent = t.label;
      sel.appendChild(opt);
    });
  }
  if (!state.selectedTopicId || !heat.topics.some(t => t.id === state.selectedTopicId)){
    state.selectedTopicId = heat.topics[0].id;
  }
  sel.value = state.selectedTopicId;
  const topic = heat.topics.find(t => t.id === state.selectedTopicId) || heat.topics[0];
  // Google Trends external link (interactive version, opens in new tab)
  const link = document.getElementById('topicTrendsLink');
  const linkLabel = document.getElementById('topicTrendsLinkLabel');
  if (link){
    link.href = buildTrendsExploreUrl(topic);
    if (linkLabel) linkLabel.textContent = `在 Google Trends 查看「${topic.label}」互動版`;
  }
  // Google Trends inline line chart (5y weekly series fetched by pytrends)
  renderTrendsChart(topic);
  // Info text
  const info = document.getElementById('topicInfo');
  if (info){
    const total = topic.our_data?.total || 0;
    const kws = (topic.match_keywords || []).join('、');
    info.textContent = `（關鍵字：${kws}　我方共 ${total} 則）`;
  }
  // Our-data bar chart
  const canvas = document.getElementById('topicOwnChart');
  if (!canvas) return;
  const daily = topic.our_data?.daily || [];
  const labels = daily.map(d => d.date);
  const counts = daily.map(d => d.count);
  topicOwnChart = upsertChart(topicOwnChart, canvas, {
    type: 'bar',
    data: {
      labels,
      datasets: [{
        label: `提及數（${topic.label}）`,
        data: counts,
        backgroundColor: '#4f8cff',
        hoverBackgroundColor: '#7fc0ff',
        borderRadius: 4,
      }],
    },
    options: {
      interaction: INDEX_HOVER,
      hover: INDEX_HOVER,
      plugins: {
        legend: { labels: { color: '#b9c3f2' } },
        tooltip: darkTooltip({
          mode: 'index',
          displayColors: false,
          callbacks: {
            title: (items) => items[0]?.label || '',
            label: (ctx) => `提及：${ctx.parsed.y} 則`,
          },
        }),
      },
      scales: {
        x: { ticks: { color: '#b9c3f2' }, grid: { color: 'rgba(120,140,200,0.08)' } },
        y: { ticks: { color: '#b9c3f2', precision: 0 }, beginAtZero: true, grid: { color: 'rgba(120,140,200,0.08)' } },
      },
    },
  });
}

function renderTrendsChart(topic){
  const canvas = document.getElementById('topicTrendsChart');
  const meta = document.getElementById('topicTrendsMeta');
  if (!canvas) return;
  const gt = topic.google_trends;
  if (!gt || !gt.points || !gt.points.length){
    // Nothing to draw — clear canvas and show a note
    if (topicTrendsChart){ topicTrendsChart.destroy(); topicTrendsChart = null; }
    const ctx = canvas.getContext('2d');
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    if (meta) meta.innerHTML = '<span class="trends-warn">⚠️ Google Trends 尚未取得資料（可能 Google 暫時封鎖 pytrends）。請稍後重跑 <code>update_topic_heat_lxy.py</code>。</span>';
    return;
  }
  const pts = gt.points;
  const labels = pts.map(p => p.date);
  const values = pts.map(p => p.value);
  const peak = values.reduce((a,b) => a > b ? a : b, 0);
  const peakIdx = values.indexOf(peak);
  const peakDate = labels[peakIdx];
  topicTrendsChart = upsertChart(topicTrendsChart, canvas, {
    type: 'line',
    data: {
      labels,
      datasets: [{
        label: `${topic.label} 熱度 (0–100)`,
        data: values,
        borderColor: '#7fc0ff',
        backgroundColor: 'rgba(127,192,255,0.18)',
        fill: true,
        tension: 0.15,
        pointRadius: 0,           // baseline: dots hidden for a clean line
        pointHoverRadius: 5,      // highlight the point under the cursor
        pointHoverBackgroundColor: '#ffffff',
        pointHoverBorderColor: '#7fc0ff',
        pointHoverBorderWidth: 2,
        borderWidth: 1.8,
      }],
    },
    options: {
      // Index mode: hover anywhere on the x-axis shows the nearest week's
      // tooltip (instead of requiring a pixel-exact hover on a data point).
      interaction: { mode: 'index', intersect: false, axis: 'x' },
      hover: { mode: 'index', intersect: false },
      plugins: {
        legend: { labels: { color: '#b9c3f2' } },
        tooltip: {
          mode: 'index',
          intersect: false,
          backgroundColor: 'rgba(18, 25, 53, 0.96)',
          borderColor: '#5a79ff',
          borderWidth: 1,
          titleColor: '#d8e2ff',
          bodyColor: '#e8ecff',
          padding: 10,
          cornerRadius: 8,
          titleFont: { weight: '600', size: 13 },
          bodyFont: { size: 13 },
          displayColors: false,
          callbacks: {
            title: (items) => items[0]?.label || '',
            label: (ctx) => `熱度：${ctx.parsed.y} / 100`,
          },
        },
      },
      scales: {
        x: {
          ticks: {
            color: '#b9c3f2',
            maxTicksLimit: 8,   // 262 個點，Chart.js 自動挑子集顯示 label
            maxRotation: 0,
            autoSkip: true,
          },
          grid: { color: 'rgba(120,140,200,0.06)' },
        },
        y: {
          beginAtZero: true, suggestedMax: 100,
          ticks: { color: '#b9c3f2', stepSize: 25 },
          grid: { color: 'rgba(120,140,200,0.08)' },
        },
      },
    },
  });
  canvas.style.cursor = 'crosshair';   // affordance: hints the line is interactive
  if (meta){
    const fetched = gt.fetched_at ? new Date(gt.fetched_at).toLocaleString('zh-TW', { hour12: false }) : '—';
    const stale = gt.stale ? `<span class="trends-warn">（快取資料，最新一次 fetch 失敗）</span>` : '';
    meta.innerHTML = `
      共 ${pts.length} 筆（週頻率）　｜　峰值 <b>${peak}</b> @ ${peakDate}　｜　抓取時間：${fetched} ${stale}
    `;
  }
}

function initTopicHeat(){
  const sel = document.getElementById('topicSelect');
  if (sel && !sel.dataset.bound){
    sel.dataset.bound = '1';
    sel.addEventListener('change', () => {
      state.selectedTopicId = sel.value;
      renderTopicHeat();
    });
  }
}

// --------- Drilldown modal ---------
const modalState = { platform: 'facebook', filter: 'all' };

function openModal(platform, filter){
  modalState.platform = platform;
  modalState.filter = filter || 'all';
  const modal = document.getElementById('commentsModal');
  if (!modal) return;
  modal.classList.remove('hidden');
  modal.setAttribute('aria-hidden', 'false');
  document.body.style.overflow = 'hidden';
  document.getElementById('modalTitle').textContent = `${PLATFORM_LABEL[platform]} 留言明細`;
  // sync filter buttons
  document.querySelectorAll('#modalFilters .filter-btn').forEach(b => {
    b.classList.toggle('active', b.dataset.filter === modalState.filter);
  });
  renderModalBody();
}

function closeModal(){
  const modal = document.getElementById('commentsModal');
  if (!modal) return;
  modal.classList.add('hidden');
  modal.setAttribute('aria-hidden', 'true');
  document.body.style.overflow = '';
}

function renderModalBody(){
  const body = document.getElementById('modalBody');
  const summary = document.getElementById('modalSummary');
  if (!body) return;
  const list = (state.comments[modalState.platform] || []);
  const filtered = modalState.filter === 'all'
    ? list
    : list.filter(c => c.signal === modalState.filter);
  const counts = { red: 0, yellow: 0, green: 0 };
  list.forEach(c => { if (counts[c.signal] != null) counts[c.signal]++; });
  if (summary) {
    summary.textContent = `共 ${list.length} 則（🔴 ${counts.red} / 🟡 ${counts.yellow} / 🟢 ${counts.green}）　｜　本視圖：${filtered.length} 則`;
  }
  body.innerHTML = '';
  if (!filtered.length){
    body.innerHTML = '<p class="hint" style="padding:20px;text-align:center">沒有符合條件的留言。</p>';
    return;
  }
  const frag = document.createDocumentFragment();
  filtered.forEach(c => {
    const div = document.createElement('div');
    div.className = 'comment-item';
    const lightClass = c.signal || 'green';
    const lightLabel = { red:'🔴 紅', yellow:'🟡 黃', green:'🟢 綠' }[lightClass] || lightClass;
    const url = c.url
      ? `<div class="linkrow"><a href="${escapeHtml(c.url)}" target="_blank" rel="noopener">原文連結 ↗</a></div>`
      : '';
    div.innerHTML = `
      <div class="hdr">
        <span class="author">${escapeHtml(c.author || '匿名')}</span>
        <span class="when">${escapeHtml(c.time_text || '')}</span>
        <span class="light-chip ${lightClass}">${lightLabel}</span>
      </div>
      <div class="text">${escapeHtml(c.text || '')}</div>
      ${url}
    `;
    frag.appendChild(div);
  });
  body.appendChild(frag);
}

function inferLocationFromText(text){
  const t = String(text || '');
  const hit = LOCATION_HINTS.find(x => t.includes(x.k));
  return hit || null;
}

function deriveCommentHotspots(){
  const out = [];
  COMMENT_EVENT_RULES.forEach(rule => {
    const platforms = new Set();
    let hits = 0;
    let inferred = null;

    ['facebook','instagram','threads'].forEach(p => {
      (state.comments[p] || []).forEach(c => {
        const txt = String(c.text || '');
        if (rule.keywords.some(k => txt.includes(k))) {
          hits += 1;
          platforms.add(PLATFORM_LABEL[p] || p);
          if (!inferred) inferred = inferLocationFromText(txt);
        }
      });
    });

    if (hits > 0) {
      out.push({
        title: rule.title,
        place: inferred?.place || rule.place,
        lat: inferred?.lat ?? rule.lat,
        lng: inferred?.lng ?? rule.lng,
        level: rule.level,
        source: 'comment',
        platform: `留言：${Array.from(platforms).join(' / ')}`,
        note: `自動偵測 ${hits} 則相關留言`
      });
    }
  });
  return out;
}

function renderIncidentMap(d){
  const mapEl = document.getElementById('incidentMap');
  if (!mapEl || typeof window.L === 'undefined') return;

  let hotspots = (Array.isArray(d.hotspots) && d.hotspots.length) ? d.hotspots : [];
  if (!hotspots.length) {
    const autoCommentHotspots = deriveCommentHotspots();
    hotspots = [...DEFAULT_HOTSPOTS, ...(autoCommentHotspots.length ? autoCommentHotspots : COMMENT_EVENT_RULES.map(r => ({
      title: r.title,
      place: r.place,
      lat: r.lat,
      lng: r.lng,
      level: r.level,
      source: 'comment',
      platform: '留言（暫無偵測到平台）',
      note: '等待留言資料觸發'
    })))];

    const suggestEl = document.getElementById('hotspotSuggestions');
    if (suggestEl) {
      const pending = COMMENT_EVENT_RULES.filter(r => !autoCommentHotspots.some(h => h.title === r.title));
      suggestEl.innerHTML = pending.length
        ? `半自動建議：以下事件目前尚未在最新留言中達到觸發條件 → ${pending.map(x => `<span class="chip">${escapeHtml(x.title)}</span>`).join('')}`
        : '半自動建議：目前規則事件皆已觸發。';
    }
  }

  if (hotspots.length && Array.isArray(d.hotspots) && d.hotspots.length) {
    const suggestEl = document.getElementById('hotspotSuggestions');
    if (suggestEl) suggestEl.textContent = '目前採用 data.json 既有 hotspots 設定（手動/外部來源）。';
  }

  if (!incidentMap) {
    incidentMap = L.map('incidentMap', { scrollWheelZoom: false }).setView([24.15, 120.67], 11);
    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      maxZoom: 18,
      attribution: '&copy; OpenStreetMap'
    }).addTo(incidentMap);
  }

  if (incidentMap._markerLayer) incidentMap.removeLayer(incidentMap._markerLayer);
  const layer = L.featureGroup();

  hotspots.forEach(h => {
    if (h.lat == null || h.lng == null) return;
    const level = h.level || 'red';
    const color = level === 'red' ? '#ff4d4f' : level === 'yellow' ? '#f7c948' : '#20c997';
    const marker = L.circleMarker([h.lat, h.lng], {
      radius: 9,
      color,
      weight: 2,
      fillColor: color,
      fillOpacity: 0.65
    });
    marker.bindPopup(`
      <div class="map-popup">
        <strong>${escapeHtml(h.title || '事件')}</strong><br/>
        地點：${escapeHtml(h.place || '-') }<br/>
        等級：${escapeHtml(level.toUpperCase())}<br/>
        來源：${escapeHtml(h.source || '-') }<br/>
        平台：${escapeHtml(h.platform || '-') }<br/>
        備註：${escapeHtml(h.note || '-') }
      </div>
    `);
    layer.addLayer(marker);
  });

  layer.addTo(incidentMap);
  incidentMap._markerLayer = layer;

  const bounds = layer.getBounds();
  if (bounds.isValid()) incidentMap.fitBounds(bounds.pad(0.25));
}

function initModal(){
  const modal = document.getElementById('commentsModal');
  if (!modal) return;
  document.getElementById('modalClose')?.addEventListener('click', closeModal);
  modal.addEventListener('click', (e) => {
    if (e.target?.dataset?.close === '1') closeModal();
  });
  document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape' && !modal.classList.contains('hidden')) closeModal();
  });
  document.querySelectorAll('#modalFilters .filter-btn').forEach(btn => {
    btn.addEventListener('click', () => {
      modalState.filter = btn.dataset.filter;
      document.querySelectorAll('#modalFilters .filter-btn').forEach(b => {
        b.classList.toggle('active', b === btn);
      });
      renderModalBody();
    });
  });
}

// --------- Main render ---------
async function run(){
  const d = await fetchJSON('./data.json');
  if (!d) return;
  const liveNow = await fetchJSON('./live_news.json') || [];

  // New signal/comment/history artefacts — optional, safe if absent
  state.socialSignals = await fetchJSON('./social_signals.json') || null;
  state.history = await fetchJSON('./social_signals_history.json') || { facebook: [], instagram: [], threads: [] };
  state.comments.facebook = await fetchJSON('./comments_facebook.json') || [];
  state.comments.instagram = await fetchJSON('./comments_instagram.json') || [];
  state.comments.threads = await fetchJSON('./comments_threads.json') || [];
  state.topicHeat = await fetchJSON('./topic_heat.json') || null;

  const m = pick(d, 'metrics', 'metrics_7d') || {};
  document.getElementById('updated').textContent = '更新時間：' + new Date(d.generated_at).toLocaleString('zh-TW',{hour12:false});
  document.getElementById('modeHint').textContent = mode==='7d' ? '（近7日聚合）' : '（近24h）';
  const mTotal = (m.total ?? m.total_24h);
  const mPrev = (m.prev ?? m.prev_24h);
  const mGrowth = m.growth_pct;
  document.getElementById('total24').textContent = mTotal ?? '-';
  document.getElementById('prev24').textContent = mPrev ?? '-';
  document.getElementById('growth').textContent = mGrowth==null ? '-' : `${mGrowth}%`;
  const parseTs = (s)=>{
    const raw = String(s||'').trim();
    if (!raw) return NaN;
    let t = Date.parse(raw); // handles RFC2822 (e.g., Mon, 04 May ... GMT)
    if (!Number.isFinite(t)) t = Date.parse(raw.replace(' ','T')); // handles YYYY-MM-DD HH:mm:ss
    return Number.isFinite(t) ? t : NaN;
  };
  const latestFallback = (pick(d,'latest_news_20')||[]).filter(x=>parseTs(x.time)).filter(x=> (Date.now()-parseTs(x.time)) <= 48*3600*1000).length;
  const live24hItems = liveNow.filter(x=>parseTs(x.time)).filter(x=> (Date.now()-parseTs(x.time)) <= 24*3600*1000);
  const livePrev24Items = liveNow.filter(x=>parseTs(x.time)).filter(x=> {
    const dt = Date.now()-parseTs(x.time);
    return dt > 24*3600*1000 && dt <= 48*3600*1000;
  });
  const live24h = live24hItems.length;
  const livePrev24 = livePrev24Items.length;
  const newsCount = (m.news ?? m.news_24h);
  document.getElementById('news24').textContent = (newsCount===0 && (live24h>0 || latestFallback>0))
    ? `${live24h || latestFallback}（fallback）`
    : (newsCount ?? '-');
  if (mode!=='7d' && mTotal===0 && live24h>0){
    const growth = livePrev24>0 ? (((live24h-livePrev24)/livePrev24)*100).toFixed(1) : '100.0';
    document.getElementById('total24').textContent = `${live24h}（live）`;
    document.getElementById('prev24').textContent = `${livePrev24}（live）`;
    document.getElementById('growth').textContent = `${growth}%（live）`;
  }

  const level = (m.anomaly||{}).level || '綠';
  document.getElementById('light').innerHTML = `<span class="badge ${level}">${LIGHT_ICON[level]||'🟢'} ${level}</span>`;

  let cmp = pick(d, 'mention_compare_24h', 'mention_compare_7d') || {};
  const cmpEmpty = mode==='24h' && Object.values(cmp).every(v => !v);
  if (cmpEmpty && live24hItems.length){
    const alias = {
      '盧秀燕':['盧秀燕','秀燕'],
      '蔣萬安':['蔣萬安','萬安'],
      '陳其邁':['陳其邁','其邁'],
      '蔡其昌':['蔡其昌','其昌']
    };
    const itemsText = live24hItems.map(x=>`${x.title||''} ${(x.url||'')}`);
    const countArticleMention = (words)=> itemsText.filter(t => words.some(w => t.includes(w))).length;
    cmp = Object.fromEntries(Object.entries(alias).map(([k,arr])=>[k, countArticleMention(arr)]));
  }
  const names = Object.keys(cmp);
  const vals = names.map(n => cmp[n] || 0);
  document.getElementById('compare').textContent = names.map(n => `${n}：${cmp[n]||0}`).join(' ｜ ');

  const byPlatform24 = d.by_platform || [];
  const byPlatformLive = live24h>0 ? [{ platform:'news', count: live24h }] : [];
  const byPlatform = byPlatform24.length ? byPlatform24 : (mode==='24h' && byPlatformLive.length ? byPlatformLive : (d.by_platform_7d || []));
  const ul = document.getElementById('platforms'); ul.innerHTML='';
  byPlatform.forEach(x=>{ const li=document.createElement('li'); li.textContent=`${x.platform}: ${x.count}`; ul.appendChild(li); });

  // Clickable social cards + alert + trend chart + red panel — all read from state
  renderSocialCards();
  updateAlertBanner();
  renderRedTrendChart();
  renderRedCommentsPanel();
  renderTopicHeat();
  renderIncidentMap(d);
  // If modal is open, re-render its body with fresh data
  const modal = document.getElementById('commentsModal');
  if (modal && !modal.classList.contains('hidden')) renderModalBody();

  const topNewsRaw = pick(d, 'top_news', 'top_news_7d') || [];
  const latestNewsList = pick(d,'latest_news_20') || [];
  const liveNews = await fetchLiveNews();
  const topNews = [...liveNews, ...topNewsRaw, ...latestNewsList]
    .filter(x=>x && x.url)
    .filter((x,i,arr)=>arr.findIndex(y=>y.url===x.url)===i);
  const news = document.getElementById('news'); news.innerHTML='';
  const displayText = (x)=>{
    const t=(x.title||'').trim();
    if(t) return t;
    try{ return new URL(x.url).hostname + '（原文）'; }catch{ return '來源連結'; }
  };
  if(!topNews.length){
    const li=document.createElement('li');
    li.textContent='目前資料源暫無可顯示新聞（可檢查 data.json 更新時間）';
    news.appendChild(li);
  }else{
    topNews.slice(0,12).forEach(x=>{
      const li=document.createElement('li');
      const a=document.createElement('a');
      a.href=x.url; a.target='_blank'; a.rel='noopener';
      a.textContent=displayText(x) + (x.time ? `（${x.time.slice(5,16)}）` : '');
      li.appendChild(a); news.appendChild(li);
    });
  }

  const detailMap24 = d.latest_by_platform_24h || {};
  const detailMapLive = live24hItems.length ? { news: live24hItems.slice(0,30) } : {};
  const detailMap = Object.keys(detailMap24).length ? detailMap24 : (mode==='24h' && Object.keys(detailMapLive).length ? detailMapLive : (d.latest_by_platform_7d || {}));
  const platformDetail = document.getElementById('platformDetail');
  if(platformDetail){
    platformDetail.innerHTML='';
    Object.keys(detailMap).forEach(p=>{
      const box=document.createElement('div'); box.className='platform-box';
      const h=document.createElement('h3'); h.textContent=`${p}（${(detailMap[p]||[]).length} 筆）`; box.appendChild(h);
      const ol=document.createElement('ol');
      (detailMap[p]||[]).forEach(x=>{
        const li=document.createElement('li');
        const a=document.createElement('a'); a.href=x.url; a.target='_blank'; a.rel='noopener';
        a.textContent=displayText(x) + (x.time ? `（${x.time.slice(5,16)}）` : '');
        li.appendChild(a); ol.appendChild(li);
      });
      box.appendChild(ol); platformDetail.appendChild(box);
    });
  }

  function renderList(elId, arr){
    const el=document.getElementById(elId); if(!el) return; el.innerHTML='';
    (arr||[]).forEach(x=>{ const li=document.createElement('li'); const a=document.createElement('a'); a.href=x.url; a.target='_blank'; a.rel='noopener'; a.textContent=displayText(x)+(x.time?`（${x.time.slice(5,16)}）`:'' ); li.appendChild(a); el.appendChild(li); });
  }
  const ps = d.person_sections || {};
  renderList('luFb', (ps['盧秀燕']||{}).facebook || []);
  renderList('luNews', (ps['盧秀燕']||{}).news || []);
  renderList('chiangFb', (ps['蔣萬安']||{}).facebook || []);
  renderList('chiangNews', (ps['蔣萬安']||{}).news || []);
  renderList('chenFb', (ps['陳其邁']||{}).facebook || []);
  renderList('chenNews', (ps['陳其邁']||{}).news || []);
  renderList('tsaiFb', (ps['蔡其昌']||{}).facebook || []);
  renderList('tsaiNews', (ps['蔡其昌']||{}).news || []);

  const byHour24 = d.by_hour || [];
  const byHourLive = (()=>{
    const map = new Map();
    live24hItems.forEach(x=>{
      const t = new Date(parseTs(x.time));
      const key = `${t.getFullYear()}-${String(t.getMonth()+1).padStart(2,'0')}-${String(t.getDate()).padStart(2,'0')} ${String(t.getHours()).padStart(2,'0')}:00`;
      map.set(key, (map.get(key)||0)+1);
    });
    return [...map.entries()].sort((a,b)=>a[0].localeCompare(b[0])).map(([hour,count])=>({hour,count}));
  })();
  const byHour = byHour24.length ? byHour24 : (mode==='24h' && byHourLive.length ? byHourLive : (d.by_hour_7d || []));

  // 燈號狀態與原因（可視化）
  let an = m.anomaly || {};
  let reasons = an.reasons || [];
  if (mode==='24h' && (mTotal===0) && live24h>0){
    const baseline = (d.by_hour_7d||[]).length
      ? (d.by_hour_7d||[]).reduce((s,x)=>s+(x.count||0),0)/(d.by_hour_7d||[]).length
      : 2;
    const cur = byHourLive.length ? (byHourLive[byHourLive.length-1].count||0) : 0;
    const lv = lightLevelByCount(cur, baseline);
    an = { level: lv, current_hour_count: cur, baseline_same_hour_7d: Number(baseline.toFixed(3)), reasons: [] };
    reasons = [`live 24h 資料推估（當前小時 ${cur}，基線 ${baseline.toFixed(2)}）`];
  }
  const es = d.event_stream || {};
  const streamTxt = `分鐘級 ${ (es.minute||[]).length }｜小時級 ${ (es.hour||[]).length }｜日級 ${ (es.day||[]).length }`;
  const ls = document.getElementById('lightStatus');
  if(ls){ ls.innerHTML = `<span class="badge ${level}">${LIGHT_ICON[level]||'🟢'} 今日燈號：${level}</span>`; }
  const lr = document.getElementById('lightReasons');
  if(lr){ lr.textContent = reasons.length ? `觸發原因：${reasons.join('；')}` : '觸發原因：無（目前屬常態）'; }
  const lstream = document.getElementById('lightStreams');
  if(lstream){ lstream.innerHTML = `<span class="badge 綠">${streamTxt}</span>`; }
  const lt = document.getElementById('lightTrend');
  if(lt){
    const avg = byHour.length ? byHour.reduce((a,b)=>a+(b.count||0),0)/byHour.length : 0;
    const last = byHour.slice(-12).map(x => ({ h:(x.hour||'').slice(11,16), lv: lightLevelByCount(x.count||0, avg) }));
    lt.innerHTML = '近12小時：' + last.map(x=>`${x.h} ${LIGHT_ICON[x.lv]}${x.lv}`).join(' ｜ ');
  }

  hourChart = upsertChart(hourChart, document.getElementById('hourChart'), {
    type:'line',
    data:{
      labels:byHour.map(x=>(x.hour||'').slice(5,16)),
      datasets:[{
        label:'聲量', data:byHour.map(x=>x.count||0),
        borderColor:'#7fc0ff', backgroundColor:'rgba(127,192,255,0.2)',
        tension:0.25, fill:true,
        pointRadius:0, pointHoverRadius:5,
        pointHoverBackgroundColor:'#fff', pointHoverBorderColor:'#7fc0ff',
      }],
    },
    options:{
      interaction: INDEX_HOVER,
      hover: INDEX_HOVER,
      plugins:{
        legend:{display:false},
        tooltip: darkTooltip({
          mode: 'index',
          displayColors: false,
          callbacks: { label: (ctx) => `聲量：${ctx.parsed.y}` },
        }),
      },
      scales:{x:{ticks:{color:'#b9c3f2'}}, y:{ticks:{color:'#b9c3f2'}, beginAtZero:true}}
    }
  });

  platformChart = upsertChart(platformChart, document.getElementById('platformChart'), {
    type:'doughnut',
    data:{ labels:byPlatform.map(x=>x.platform), datasets:[{data:byPlatform.map(x=>x.count), backgroundColor:['#4f8cff','#20c997','#ffc107','#e83e8c','#fd7e14','#6f42c1','#adb5bd']}] },
    options:{
      plugins:{
        legend:{labels:{color:'#b9c3f2'}},
        tooltip: darkTooltip({
          callbacks: {
            label: (ctx) => {
              const total = ctx.dataset.data.reduce((a,b)=>a+b, 0);
              const pct = total ? (ctx.parsed / total * 100).toFixed(1) : 0;
              return ` ${ctx.label}：${ctx.parsed}（${pct}%）`;
            },
          },
        }),
      },
    }
  });

  mentionChart = upsertChart(mentionChart, document.getElementById('mentionChart'), {
    type:'bar',
    data:{
      labels:names,
      datasets:[{
        label:'提及數', data:vals,
        backgroundColor:['#20c997','#4f8cff','#ffc107','#e83e8c','#fd7e14'],
        borderRadius:4,
        hoverBackgroundColor:'#ffffff40',
      }],
    },
    options:{
      interaction: INDEX_HOVER,
      hover: INDEX_HOVER,
      plugins:{
        legend:{display:false},
        tooltip: darkTooltip({
          mode: 'index',
          displayColors: false,
          callbacks: { label: (ctx) => `提及：${ctx.parsed.y} 則` },
        }),
      },
      scales:{x:{ticks:{color:'#b9c3f2'}}, y:{ticks:{color:'#b9c3f2'}, beginAtZero:true}}
    }
  });
}

function initCollapsibles(){
  document.querySelectorAll('.panel-toggle').forEach(btn=>{
    if(btn.dataset.bound==='1') return;
    btn.dataset.bound='1';
    btn.addEventListener('click', ()=>{
      const expanded = btn.getAttribute('aria-expanded') === 'true';
      btn.setAttribute('aria-expanded', String(!expanded));
      const panel = btn.closest('.collapsible');
      if(panel) panel.classList.toggle('collapsed', expanded);
    });
  });
}

function initModes(){
  const b24 = document.getElementById('mode24');
  const b7 = document.getElementById('mode7d');
  if(b24) b24.onclick = async ()=>{ mode='24h'; await run(); };
  if(b7) b7.onclick = async ()=>{ mode='7d'; await run(); };
}

initCollapsibles();
initModes();
initModal();
initTopicHeat();
run();
setInterval(run,60000);
